spring:
  jpa:
    #    open-in-view: false
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      jdbc.lob.non_contextual_creation: true

  datasource:
    platform: mysql
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver


tgnotifier:
  telegramToken:
  wsUrl:
  showDescriptions: false

logging:
  level:
    pro:
      belbix:
        ethparser:
          web3:
            uniswap: TRACE
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
