# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Pull Request script

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: harvest
          POSTGRES_USER: harvest
          POSTGRES_DB: harvest
        ports:
          - 5432:5432
        options:
          --health-cmd=pg_isready --health-interval=10s --health-timeout=5s --health-retries=5


    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Maven
        run: mvn -Dtgnotifier.telegramToken="${{secrets.TELEGRAM_TOKEN}}" -Dtgnotifier.wsUrl="https://ethparser-api.herokuapp.com/stomp" -Dspring.datasource.url=jdbc:postgresql://localhost:5432/harvest -Dspring.datasource.username=harvest -Dspring.datasource.password=harvest -B package -ff -T 1 --file pom.xml